name: Format Python
on:
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Format code with black
        run: |
          pip install black
          black --line-length 120 .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Formatted code with black --line-length 120"
          add: "."
