name: Format Python
on:
  pull_request:
    types: [ opened, edited, reopened, synchronize, ready_for_review ]
  workflow_dispatch:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Format code with black
        run: |
          pip install black
          black --line-length 120 .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Formatted code with black --line-length 120"
          add: "."
